FROM quay.io/keycloak/keycloak:26.2 AS builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
#ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:example.rhbk.com,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
#ENV KC_DB=postgres
#ENV KC_DB_URL=jdbc:postgresql://keycloakdb/auth-database
#ENV KC_DB_USERNAME=keycloakuser
#ENV KC_DB_PASSWORD=keycloakpass1234
ENV KC_HOSTNAME=example.keycloak.com
#ENV QUARKUS_HTTP_ACCESS_LOG_ENABLED=true

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]